import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {  ThemeProviders } from "./ThemeProviders";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-pt">
      <body className={inter.className}>
      <Toaster toastOptions={{
          style: {
            backgroundColor: 'rgb(51, 65, 85)',
            color: '#fff'
          }
        }} />
        <ThemeProviders>
          {children}
        </ThemeProviders>
      </body>
    </html>
  );
}
